@startuml

!define PRIMARY_KEY(x) x INT PRIMARY KEY AUTO_INCREMENT
!define FOREIGN_KEY(x) x INT, FOREIGN KEY (x) REFERENCES User(id)

entity "User" {
  +PRIMARY_KEY(id)
  fullName VARCHAR(255) NOT NULL
  email VARCHAR(255) UNIQUE NOT NULL
  password VARCHAR(255) NOT NULL
  token VARCHAR(255)
  expirationTime DATETIME
}

entity "Email" {
  +PRIMARY_KEY(id)
  +FOREIGN_KEY(senderId)
  +FOREIGN_KEY(recipientId)
  subject VARCHAR(255)
  body TEXT
  timeSent DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted_by_sender BOOLEAN DEFAULT FALSE
  deleted_by_receiver BOOLEAN DEFAULT FALSE
}

entity "Attachment" {
  +PRIMARY_KEY(id)
  +FOREIGN_KEY(emailId)
  fileName VARCHAR(255)
  fileData BLOB
}

User --o{ Email : senderId
User --o{ Email : recipientId
Email --o{ Attachment : emailId

@enduml
